name: Publish the node package

on:
  # publish the package if I directly push to master or if I merge a pull request
  push:
    branches:
      - master
    path-ignore:
      - "**.md"

jobs:
  npm:
    name: npm
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository to local runner
        uses: actions/checkout@v2

      - name: Install Node Version 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
          registry-url: https://registry.npmjs.org/

      - name: Installing dependencies
        run: yarn --immutable

      - name: Removing the test directory
        run: rm -r src/test-bot/

      - name: Builing
        run: yarn build

      - name: Publishing the package to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
